import { useTranslation } from "react-i18next";
import type { AiContextDisclosureView } from "../../../app/ai-state";
import type { AssistantContextReceipt } from "../../../app/assistant-context";
import { Disclosure } from "../../ui/Disclosure";

export function AssistantContextReceiptView({ receipt, preview }: { receipt: AssistantContextReceipt | null; preview: AiContextDisclosureView | null }) {
  const { t } = useTranslation();
  if (!receipt) return <p className="assistant-safe-note">{t("assistant.receipt.noContext")}</p>;
  return <section className="assistant-context-receipt" aria-labelledby="assistant-context-receipt-title"><h3 id="assistant-context-receipt-title">{t("assistant.receipt.title")}</h3><dl><div><dt>{t("assistant.receipt.project")}</dt><dd>{receipt.project ?? "—"}</dd></div><div><dt>{t("assistant.receipt.revision")}</dt><dd>{receipt.revision ?? "—"}</dd></div><div><dt>{t("assistant.receipt.object")}</dt><dd>{receipt.object ?? "—"}</dd></div><div><dt>{t("assistant.receipt.run")}</dt><dd>{receipt.run?.slice(0, 12) ?? "—"}</dd></div><div><dt>{t("assistant.receipt.dataset")}</dt><dd>{receipt.resultDatasetFingerprint?.slice(0, 12) ?? "—"}</dd></div><div><dt>{t("assistant.receipt.metricTime")}</dt><dd>{receipt.metric ? `${t(`resultsWorkspace.metric.${receipt.metric}`)} · ${receipt.selectedTimeSeconds ?? "—"} s` : "—"}</dd></div><div><dt>{t("assistant.receipt.attachments")}</dt><dd>{receipt.attachmentCount}</dd></div><div><dt>{t("assistant.receipt.network")}</dt><dd>{t(receipt.network ? "assistant.receipt.willUseNetwork" : "assistant.receipt.noNetwork")}</dd></div></dl><p>{t("assistant.receipt.excluded")}: {receipt.excluded.map((item) => t(`assistant.receipt.excludedItems.${item}`)).join("、")}</p><Disclosure label={t("assistant.receipt.advanced")}><p>{t("assistant.includedScopes")}: {receipt.includedScopes.map((scope) => t(`assistant.scopes.${scope}`)).join(", ") || "—"}</p>{preview ? <pre>{JSON.stringify({ context_fingerprint: preview.context_fingerprint, analysis_selection: preview.analysis_selection, included_scopes: preview.included_scopes, excluded_scopes: preview.excluded_scopes }, null, 2)}</pre> : null}</Disclosure></section>;
}
