import { renderToStaticMarkup } from "react-dom/server";
import { beforeAll, describe, expect, it } from "vitest";
import i18n from "../i18n";
import { CodexAssistantPanel } from "../components/workbench/CodexAssistantPanel";
import {
  aiReducer,
  INITIAL_AI_STATE,
  isSafeAiPreview,
  isStructuredAiAnswer,
  type AiContextDisclosureView,
  type CodexConnectionView,
} from "./ai-state";

const connection: CodexConnectionView = {
  status: "available",
  cli: { found: true, version: "codex-cli 1.2.3", source: "path" },
  account: { authenticated: true, auth_mode: "chatgpt", plan_type: "plus", requires_login: false },
  models: [{
    id: "model-a",
    display_name: "Model A",
    is_default: true,
    available: true,
    reasoning_efforts: [{ id: "low", description: "Low" }, { id: "high", description: "High" }],
    default_reasoning_effort: "low",
  }],
};

const preview: AiContextDisclosureView = {
  preview_id: "preview-1",
  project_session_id: "session-1",
  revision_id: "00000000-0000-5000-8000-000000000001",
  revision_number: 1,
  zone_id: "00000000-0000-5000-8000-000000000002",
  zone_name: "One",
  included_scopes: ["selected_zone", "draft_summary"],
  excluded_scopes: ["project_summary", "run_summary", "result_summary", "diagnostics"],
  context_fingerprint: "fingerprint-1",
  payload: { selected_zone: { name: "One", volume_m3: 600 }, draft_summary: { revision_number: 1 } },
  disclosure: {
    contains_local_paths: false,
    contains_prj_text: false,
    contains_complete_result_series: false,
    model_request_uses_network: true,
  },
};

beforeAll(async () => {
  await i18n.changeLanguage("en");
});

describe("read-only AI state", () => {
  it("does not connect until the user explicitly starts a connection", () => {
    expect(INITIAL_AI_STATE.status).toBe("disabled");
    expect(INITIAL_AI_STATE.connection).toBeNull();
  });

  it("uses the server model order and default reasoning effort", () => {
    const connecting = aiReducer(INITIAL_AI_STATE, { type: "connect_started", requestId: "r1" });
    const ready = aiReducer(connecting, { type: "connect_succeeded", requestId: "r1", connection });
    expect(ready.status).toBe("available");
    expect(ready.modelId).toBe("model-a");
    expect(ready.reasoningEffort).toBe("low");
    expect(ready.connection?.models[0].reasoning_efforts.map((item) => item.id)).toEqual(["low", "high"]);
  });

  it("defaults to only the selected Zone and draft summary", () => {
    expect(INITIAL_AI_STATE.scopes).toEqual(["selected_zone", "draft_summary"]);
  });

  it("invalidates preview and answer when a scope, model, or trusted context changes", () => {
    const populated = { ...INITIAL_AI_STATE, connection, status: "available" as const, preview, answer: { deterministic_facts: ["x"], interpretation: "y", limitations: [], suggested_questions: [] } };
    expect(aiReducer(populated, { type: "scope_toggled", scope: "run_summary" }).preview).toBeNull();
    expect(aiReducer(populated, { type: "model_changed", modelId: "model-a", effort: "high" }).answer).toBeNull();
    expect(aiReducer(populated, { type: "context_changed" }).question).toBe("");
  });

  it("ignores stale connection and turn responses", () => {
    const connecting = aiReducer(INITIAL_AI_STATE, { type: "connect_started", requestId: "current" });
    expect(aiReducer(connecting, { type: "connect_succeeded", requestId: "old", connection })).toEqual(connecting);
    const generating = aiReducer({ ...connecting, status: "available" }, { type: "turn_started", requestId: "turn-current" });
    expect(aiReducer(generating, { type: "turn_succeeded", requestId: "turn-old", answer: { deterministic_facts: [], interpretation: "", limitations: [], suggested_questions: [] }, tokenUsage: null })).toEqual(generating);
  });

  it("accepts only a path-free disclosure generated by Rust", () => {
    expect(isSafeAiPreview(preview)).toBe(true);
    expect(isSafeAiPreview({ ...preview, payload: { source: "C:\\private\\project.prj" } })).toBe(false);
    expect(isSafeAiPreview({ ...preview, disclosure: { ...preview.disclosure, contains_prj_text: true } as never })).toBe(false);
  });

  it("validates the closed structured answer shape and limits", () => {
    expect(isStructuredAiAnswer({ deterministic_facts: ["fact"], interpretation: "interpretation", limitations: ["limit"], suggested_questions: ["next?"] })).toBe(true);
    expect(isStructuredAiAnswer({ deterministic_facts: ["x".repeat(1201)], interpretation: "", limitations: [], suggested_questions: [] })).toBe(false);
    expect(isStructuredAiAnswer({ deterministic_facts: [], interpretation: "x".repeat(4001), limitations: [], suggested_questions: [] })).toBe(false);
    expect(isStructuredAiAnswer({ deterministic_facts: [], interpretation: "ok", limitations: [], suggested_questions: [], raw_path: "C:\\private" })).toBe(false);
  });

  it("renders network disclosure, context preview, and separate answer sections", () => {
    const html = renderToStaticMarkup(
      <CodexAssistantPanel
        state={{
          ...INITIAL_AI_STATE,
          status: "available",
          connection,
          modelId: "model-a",
          reasoningEffort: "low",
          preview,
          answer: { deterministic_facts: ["Volume is 600 m3."], interpretation: "Large volume.", limitations: ["No full series."], suggested_questions: [] },
        }}
        contextAvailable
        onConnect={() => undefined}
        onRefresh={() => undefined}
        onDisconnect={() => undefined}
        onScopeToggle={() => undefined}
        onModelChange={() => undefined}
        onEffortChange={() => undefined}
        onPreview={() => undefined}
        onQuestionChange={() => undefined}
        onSend={() => undefined}
        onStop={() => undefined}
        onClear={() => undefined}
      />,
    );
    expect(html).toContain("Local client, online model");
    expect(html).toContain("Structured context preview");
    expect(html).toContain("Deterministic facts");
    expect(html).toContain("AI interpretation");
    expect(html).toContain("Limitations");
    expect(html).not.toContain("C:\\");
  });

  it("shows the terminal login instruction without exposing account details", () => {
    const html = renderToStaticMarkup(
      <CodexAssistantPanel
        state={{
          ...INITIAL_AI_STATE,
          status: "not_authenticated",
          connection: {
            ...connection,
            account: {
              authenticated: false,
              auth_mode: null,
              plan_type: null,
              requires_login: true,
            },
            models: [],
          },
        }}
        contextAvailable
        onConnect={() => undefined}
        onRefresh={() => undefined}
        onDisconnect={() => undefined}
        onScopeToggle={() => undefined}
        onModelChange={() => undefined}
        onEffortChange={() => undefined}
        onPreview={() => undefined}
        onQuestionChange={() => undefined}
        onSend={() => undefined}
        onStop={() => undefined}
        onClear={() => undefined}
      />,
    );
    expect(html).toContain("codex login");
    expect(html).not.toContain("email");
    expect(html).not.toContain("user_id");
  });

  it("renders a stop action while a turn is generating", () => {
    const html = renderToStaticMarkup(
      <CodexAssistantPanel
        state={{
          ...INITIAL_AI_STATE,
          status: "generating",
          connection,
          modelId: "model-a",
          reasoningEffort: "low",
          preview,
          question: "Explain this Zone.",
        }}
        contextAvailable
        onConnect={() => undefined}
        onRefresh={() => undefined}
        onDisconnect={() => undefined}
        onScopeToggle={() => undefined}
        onModelChange={() => undefined}
        onEffortChange={() => undefined}
        onPreview={() => undefined}
        onQuestionChange={() => undefined}
        onSend={() => undefined}
        onStop={() => undefined}
        onClear={() => undefined}
      />,
    );
    expect(html).toContain("Stop");
    expect(html).toContain("Generating");
    expect(html).not.toContain(">Send<");
  });

  it("clears the active turn and preview on interruption or disconnection", () => {
    const generating = {
      ...INITIAL_AI_STATE,
      status: "generating" as const,
      connection,
      preview,
      question: "Explain this Zone.",
      activeRequestId: "turn-1",
    };
    const interrupted = aiReducer(generating, { type: "turn_interrupted" });
    expect(interrupted.status).toBe("available");
    expect(interrupted.preview).toEqual(preview);
    expect(interrupted.answer).toBeNull();
    const disconnected = aiReducer(interrupted, { type: "disconnected" });
    expect(disconnected).toEqual(INITIAL_AI_STATE);
  });

  it("renders the Chinese network and context disclosure labels", async () => {
    await i18n.changeLanguage("zh-CN");
    const html = renderToStaticMarkup(
      <CodexAssistantPanel
        state={{ ...INITIAL_AI_STATE, status: "available", connection, preview }}
        contextAvailable
        onConnect={() => undefined}
        onRefresh={() => undefined}
        onDisconnect={() => undefined}
        onScopeToggle={() => undefined}
        onModelChange={() => undefined}
        onEffortChange={() => undefined}
        onPreview={() => undefined}
        onQuestionChange={() => undefined}
        onSend={() => undefined}
        onStop={() => undefined}
        onClear={() => undefined}
      />,
    );
    expect(html).toContain("本地客户端，联网模型");
    expect(html).toContain("结构化上下文预览");
    expect(html).toContain("不包含绝对路径、PRJ正文或完整结果序列");
    await i18n.changeLanguage("en");
  });
});
